version: '3'

services:
  emqx:
    image: emqx:5.3.0
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
          - node1.emqx.io
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 
    # volumes:
    #   - $PWD/emqx1_data:/opt/emqx/data

  mqtt-publisher:
    build: mqtt_publisher
    depends_on:
      emqx:
        condition: service_healthy
    environment:
      - MQTT_BROKER_HOST=emqx
      - MQTT_BROKER_PORT=1883
    networks:
      emqx-bridge:
        aliases:
          - mqtt-publisher
  
  mqtt-subscriber:
    build: mqtt_subscriber
    depends_on:
      emqx:
        condition: service_healthy
    environment:
      - MQTT_BROKER_HOST=emqx
      - MQTT_BROKER_PORT=1883
    networks:
      emqx-bridge:
        aliases:
          - mqtt-subscriber

networks:
  emqx-bridge:
    driver: bridge
